language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"

matrix:
    include:
        - dist: xenial
          language: python
          python: 3.7
        - dist: xenial
          language: python
          python: 3.8
    allow_failures:
        - python: "3.4"
        - python: "pypy3"
        - python: "nightly"

install:
    - ./bootstrap.sh

script:
    - pre-commit run --all-files
    - inv test
    - inv e2e-test
    - inv benchmark

after_success:
    - codecov
