language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"

matrix:
    include:
        - dist: xenial
          language: python
          python: 3.7
    allow_failures:
        - python: "pypy3"
        - python: "nightly"

install:
    - ./bootstrap.sh

script:
    - pre-commit run --all-files
    - pytest --cov validr
    - inv build
    - pip install --ignore-installed dist/*
    - pytest
    - python benchmark/benchmark.py benchmark

after_success:
    - codecov
